# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainScreen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1267, 712)
        MainWindow.setStyleSheet("background-color:#f3f3f3;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.heading_widget = QtWidgets.QWidget(self.centralwidget)
        self.heading_widget.setMinimumSize(QtCore.QSize(0, 45))
        self.heading_widget.setMaximumSize(QtCore.QSize(16777215, 55))
        self.heading_widget.setStyleSheet("background-color:#f3f3f3;")
        self.heading_widget.setObjectName("heading_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.heading_widget)
        self.gridLayout.setContentsMargins(0, 0, 9, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.heading_widget)
        self.label.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:White;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: black;\n"
"padding:45px;\n"
"color:black;\n"
"font:Bold;\n"
"font-size: 30px")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.heading_widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background-color:#f3f3f3;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMaximumSize(QtCore.QSize(500, 600))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(-1, -1, -1, 50)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("background-color:#f3f3f3;")
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setPixmap(QtGui.QPixmap("ACENXION LOGO 2 Transparent.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.back_btn = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        self.back_btn.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.back_btn.setObjectName("back_btn")
        self.gridLayout_3.addWidget(self.back_btn, 0, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 550))
        self.widget_3.setMaximumSize(QtCore.QSize(800, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setContentsMargins(9, 20, 9, 50)
        self.gridLayout_2.setHorizontalSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.close_door_1 = QtWidgets.QPushButton(self.widget_3)
        self.close_door_1.setMinimumSize(QtCore.QSize(350, 0))
        self.close_door_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.close_door_1.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.close_door_1.setObjectName("close_door_1")
        self.gridLayout_2.addWidget(self.close_door_1, 2, 0, 1, 1)
        self.open_door_2 = QtWidgets.QPushButton(self.widget_3)
        self.open_door_2.setMinimumSize(QtCore.QSize(350, 0))
        self.open_door_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.open_door_2.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.open_door_2.setObjectName("open_door_2")
        self.gridLayout_2.addWidget(self.open_door_2, 0, 1, 1, 1)
        self.eject_cassettle_1 = QtWidgets.QPushButton(self.widget_3)
        self.eject_cassettle_1.setMinimumSize(QtCore.QSize(350, 0))
        self.eject_cassettle_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.eject_cassettle_1.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.eject_cassettle_1.setObjectName("eject_cassettle_1")
        self.gridLayout_2.addWidget(self.eject_cassettle_1, 3, 0, 1, 1)
        self.insert_cassettle_1 = QtWidgets.QPushButton(self.widget_3)
        self.insert_cassettle_1.setMinimumSize(QtCore.QSize(350, 0))
        self.insert_cassettle_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.insert_cassettle_1.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.insert_cassettle_1.setObjectName("insert_cassettle_1")
        self.gridLayout_2.addWidget(self.insert_cassettle_1, 1, 0, 1, 1)
        self.insert_cassettle_2 = QtWidgets.QPushButton(self.widget_3)
        self.insert_cassettle_2.setMinimumSize(QtCore.QSize(350, 0))
        self.insert_cassettle_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.insert_cassettle_2.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.insert_cassettle_2.setObjectName("insert_cassettle_2")
        self.gridLayout_2.addWidget(self.insert_cassettle_2, 1, 1, 1, 1)
        self.close_door_2 = QtWidgets.QPushButton(self.widget_3)
        self.close_door_2.setMinimumSize(QtCore.QSize(350, 0))
        self.close_door_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.close_door_2.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.close_door_2.setObjectName("close_door_2")
        self.gridLayout_2.addWidget(self.close_door_2, 2, 1, 1, 1)
        self.open_door_1 = QtWidgets.QPushButton(self.widget_3)
        self.open_door_1.setMinimumSize(QtCore.QSize(350, 0))
        self.open_door_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.open_door_1.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.open_door_1.setObjectName("open_door_1")
        self.gridLayout_2.addWidget(self.open_door_1, 0, 0, 1, 1)
        self.eject_cassettle_2 = QtWidgets.QPushButton(self.widget_3)
        self.eject_cassettle_2.setMinimumSize(QtCore.QSize(350, 0))
        self.eject_cassettle_2.setStyleSheet("QPushButton{\n"
"border-color: white;\n"
"background-color:#0074a9;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: white;\n"
"padding: 16px;\n"
"color:White;\n"
"Font:Bold;\n"
"font-size: 20px\n"
"}\n"
"QPushButton:pressed{ \n"
"   border-color: black;\n"
"background-color:green;\n"
"}\n"
"")
        self.eject_cassettle_2.setObjectName("eject_cassettle_2")
        self.gridLayout_2.addWidget(self.eject_cassettle_2, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.widget_3, 0, QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Stepper Motor Test"))
        self.back_btn.setText(_translate("MainWindow", "Back"))
        self.close_door_1.setText(_translate("MainWindow", "Close Door 1"))
        self.open_door_2.setText(_translate("MainWindow", "Open Door 2"))
        self.eject_cassettle_1.setText(_translate("MainWindow", "Eject Cassettle 1"))
        self.insert_cassettle_1.setText(_translate("MainWindow", "Insert Cassettle 1"))
        self.insert_cassettle_2.setText(_translate("MainWindow", "Insert Cassettle 2"))
        self.close_door_2.setText(_translate("MainWindow", "Close Door 2"))
        self.open_door_1.setText(_translate("MainWindow", "Open Door 1"))
        self.eject_cassettle_2.setText(_translate("MainWindow", "Eject Cassettle 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainScreen()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
